#!/usr/bin/env python3
"""
Sora-Ai – Text to Video Telegram Bot
Author / Dev: FNxDANGER
"""

import os
import logging
import requests
from urllib.parse import quote

from telegram import Update
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    filters,
)

# =============== Logging ===============
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger("Sora-Ai")

# =============== Config ================
BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

# Text-to-video API (Sora-style)
TEXT2VIDEO_API = "https://texttovideov2.alphaapi.workers.dev/api/"  # ?prompt=...


# =============== Handlers ==============
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    user = update.effective_user
    await update.message.reply_text(
        f"Hi {user.first_name} 👋\n\n"
        f"Welcome to <b>Sora-Ai</b> – a Text to Video bot crafted by <b>FNxDANGER</b>. 🔥\n\n"
        f"Send any prompt and I’ll generate a short AI video for you.\n\n"
        f"<b>Examples:</b>\n"
        f"• a girl dancing\n"
        f"• train running in snowy mountains\n"
        f"• cyberpunk city at night with neon lights\n\n"
        f"Commands:\n"
        f"/start – show this message\n"
        f"/help – how to use",
        parse_mode="HTML",
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(
        "📖 *Sora-Ai – Text to Video (by FNxDANGER)*\n\n"
        "*How to use:*\n"
        "1. Type a text description of the scene you want.\n"
        "2. Send it to this bot.\n"
        "3. Wait while the AI generates a video (a few seconds to ~1 minute).\n\n"
        "*Prompt tips:*\n"
        "• Be specific: `a dog surfing a huge wave at sunset`.\n"
        "• Keep it clear and not too long.\n\n"
        "The bot will reply with a video based on your text. 🎬",
        parse_mode="Markdown",
    )


async def generate_video(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Take user text, call text-to-video API, send video back."""
    if not update.message or not update.message.text:
        return

    prompt = update.message.text.strip()
    if not prompt:
        await update.message.reply_text("❌ Please send a non‑empty text prompt.")
        return

    # Feedback to user
    processing = await update.message.reply_text(
        "⏳ Sora-Ai is generating your video...\nPlease wait, this can take a bit."
    )

    try:
        # Build API URL
        encoded_prompt = quote(prompt)
        api_url = f"{TEXT2VIDEO_API}?prompt={encoded_prompt}"

        logger.info("FNxDANGER – Requesting video for prompt: %s", prompt)
        logger.info("API URL: %s", api_url)

        headers = {
            "User-Agent": "Sora-Ai-TelegramBot/FNxDANGER",
        }

        resp = requests.get(api_url, headers=headers, timeout=180)
        status = resp.status_code
        ctype = (resp.headers.get("Content-Type") or "").lower()

        logger.info("API status=%s content-type=%s", status, ctype)

        if status != 200:
            await processing.edit_text(
                f"❌ Text‑to‑video API failed (status {status}).\n"
                f"Try again later."
            )
            return

        # Case 1: JSON with a video URL
        if "application/json" in ctype or (
            len(resp.content) < 10000 and resp.text.strip().startswith("{")
        ):
            try:
                data = resp.json()
                logger.info("API JSON: %s", data)

                if "error" in data:
                    await processing.edit_text(
                        f"❌ API error: {data.get('error')}\n"
                        "Try a different prompt."
                    )
                    return

                video_url = (
                    data.get("video_url")
                    or data.get("url")
                    or data.get("video")
                    or data.get("result")
                    or data.get("videoUrl")
                )

                if not video_url:
                    await processing.edit_text(
                        "❌ Could not find video URL in API response.\n"
                        "Please try again with another prompt."
                    )
                    logger.error("No video_url in JSON: %s", data)
                    return

                # Send video by URL
                await update.message.reply_video(
                    video=video_url,
                    caption=f'🎬 Generated by Sora-Ai (FNxDANGER)\nPrompt: "{prompt}"',
                )
                await processing.delete()
                return

            except Exception as e:
                logger.error("JSON parse/send error: %s", e, exc_info=True)
                await processing.edit_text(
                    "❌ Invalid response from generation API.\nPlease try again."
                )
                return

        # Case 2: Direct binary video
        if "video" in ctype or len(resp.content) > 10000:
            try:
                await update.message.reply_video(
                    video=resp.content,
                    caption=f'🎬 Generated by Sora-Ai (FNxDANGER)\nPrompt: "{prompt}"',
                )
                await processing.delete()
                return
            except Exception as e:
                logger.error("Error sending binary video: %s", e, exc_info=True)
                await processing.edit_text(
                    "❌ Generated video is too big or failed to send.\nPlease try again."
                )
                return

        # Fallback: unknown format
        logger.error("Unknown API response format: %s", resp.text[:300])
        await processing.edit_text(
            "❌ Unexpected response from text‑to‑video API.\nTry again later."
        )

    except requests.Timeout:
        logger.error("API timeout (FNxDANGER Sora-Ai)")
        await processing.edit_text(
            "⏰ Generation timed out.\nThe server might be busy, please try again."
        )
    except Exception as e:
        logger.error("Unhandled error in Sora-Ai: %s", e, exc_info=True)
        await processing.edit_text(
            "❌ An internal error occurred.\nPlease try again."
        )


# =============== Main ==================
def main() -> None:
    if not BOT_TOKEN:
        logger.error("TELEGRAM_BOT_TOKEN is not set in environment.")
        raise SystemExit("Set TELEGRAM_BOT_TOKEN env variable and restart Sora-Ai bot.")

    app = Application.builder().token(BOT_TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("help", help_command))
    app.add_handler(
        MessageHandler(filters.TEXT & ~filters.COMMAND, generate_video)
    )

    logger.info("Sora-Ai (FNxDANGER) bot started.")
    app.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
